# -*- coding: utf-8 -*-
"""dice_probability_simulation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j1bkXi9F2mJAedhkEggqdjXcf8n_ZoF1
"""

import random

def calculate_probability(target_sum, trials=100000):
    success_count = 0

    for _ in range(trials):
        # Ρίχνουμε δύο ζάρια
        die1 = random.randint(1, 6)
        die2 = random.randint(1, 6)

        # Ελέγχουμε αν το άθροισμα είναι αυτό που θέλουμε
        if die1 + die2 == target_sum:
            success_count += 1

    # Υπολογισμός πιθανότητας
    probability = (success_count / trials) * 100
    return probability

# --- Κύριο Πρόγραμμα ---
print("--- Υπολογιστής Πιθανοτήτων με Προσομοίωση ---")
try:
    target = int(input("Ποιο άθροισμα σε ενδιαφέρει (2 έως 12); "))

    if 2 <= target <= 12:
        prob = calculate_probability(target)
        print(f"\nΜετά από 100,000 δοκιμές:")
        print(f"Η πιθανότητα να φέρεις άθροισμα {target} είναι περίπου: {prob:.2f}%")
    else:
        print("Παρακαλώ δώσε έναν αριθμό ανάμεσα στο 2 και το 12.")

except ValueError:
    print("Σφάλμα: Πρέπει να δώσεις ακέραιο αριθμό.")